### ISSUE TITLE
bypass MBR check?

### ISSUE THREAD

**Issue by Buster14** [haithamaouati/BW11#24]
I need legacy partition for a diskless program, think its lossible to bypass it as well? googled but came up nothing

**Comment by haithamaouati** [comment]
Bypassing the Master Boot Record (MBR) check in Windows 11 is trickier, as modern Windows versions, particularly Windows 11, require UEFI and GPT (GUID Partition Table) by default. There isn't a straightforward registry key like with TPM or Secure Boot bypasses, as MBR is a fundamental part of how the system boots.

**Comment by haithamaouati** [comment]
Bypassing the Master Boot Record (MBR) check in Windows 11 is trickier, as modern Windows versions, particularly Windows 11, require UEFI and GPT (GUID Partition Table) by default. There isn't a straightforward registry key like with TPM or Secure Boot bypasses, as MBR is a fundamental part of how the system boots.
